export type Major='MAM'|'ICS'|'Econ'|'Stat';
export type DegreeTrack='dual'|'single';
export type CourseKind='common'|'shared'|'major'|'optional';
export type TimetableEvent={
  id:string; year:number; title:string; english?:string; day:number; start:number; span:number;
  room?:string; majors:Major[]|'all'; groups?:string[]; kind:CourseKind; weeks?:string; note?:string;
  track?:DegreeTrack; teacher?:string;
};

const y1English:TimetableEvent[]=[
  ['E1','英语写作 I','English Writing I',1,0,2,'N422','MAM1'],['E1','英语阅读 I','English Reading I',2,9,2,'N432','MAM1'],['E1','英语听说 I','Listening & Speaking English I',4,5,2,'N423','MAM1'],
  ['E2','英语写作 I','English Writing I',1,0,2,'N423','MAM2'],['E2','英语阅读 I','English Reading I',2,7,2,'N432','MAM2'],['E2','英语听说 I','Listening & Speaking English I',4,0,2,'N423','MAM2'],
  ['E3','英语写作 I','English Writing I',2,7,2,'N423','MAM3'],['E3','英语阅读 I','English Reading I',1,9,2,'N432','MAM3'],['E3','英语听说 I','Listening & Speaking English I',1,0,2,'N432','MAM3'],
  ['E4','英语写作 I','English Writing I',1,2,2,'N422','ICS1'],['E4','英语阅读 I','English Reading I',1,0,2,'N426','ICS1'],['E4','英语听说 I','Listening & Speaking English I',2,0,2,'N432','ICS1'],
  ['E5','英语写作 I','English Writing I',1,2,2,'N423','ICS2'],['E5','英语阅读 I','English Reading I',2,0,2,'N422','ICS2'],['E5','英语听说 I','Listening & Speaking English I',0,5,2,'N426','ICS2'],
  ['E6','英语写作 I','English Writing I',2,2,2,'N423','ICS3'],['E6','英语阅读 I','English Reading I',4,0,2,'N432','ICS3'],['E6','英语听说 I','Listening & Speaking English I',0,7,1,'N426','ICS3'],
  ['E7','英语写作 I','English Writing I',1,5,2,'N422','Econ1'],['E7','英语阅读 I','English Reading I',2,2,2,'N432','Econ1'],['E7','英语听说 I','Listening & Speaking English I',0,2,2,'N422','Econ1'],
  ['E8','英语写作 I','English Writing I',1,5,2,'N423','Econ2'],['E8','英语阅读 I','English Reading I',4,2,2,'N432','Econ2'],['E8','英语听说 I','Listening & Speaking English I',2,2,2,'N422','Econ2'],
  ['E9','英语写作 I','English Writing I',0,5,2,'N423','Econ3'],['E9','英语阅读 I','English Reading I',2,7,2,'N422','Econ3'],['E9','英语听说 I','Listening & Speaking English I',0,7,2,'N423','Econ3'],
  ['E10','英语写作 I','English Writing I',1,6,2,'N422','Stat1'],['E10','英语阅读 I','English Reading I',4,2,2,'N426','Stat1'],['E10','英语听说 I','Listening & Speaking English I',0,7,2,'N422','Stat1'],
  ['E11','英语写作 I','English Writing I',0,7,2,'N432','Stat2'],['E11','英语阅读 I','English Reading I',1,7,2,'N432','Stat2'],['E11','英语听说 I','Listening & Speaking English I',0,5,2,'N422','Stat2'],
  ['E12','英语写作 I','English Writing I',1,7,2,'N426','Stat3'],['E12','英语阅读 I','English Reading I',4,0,2,'N426','Stat3'],['E12','英语听说 I','Listening & Speaking English I',4,2,2,'N423','Stat3'],
].map((x,index)=>({id:`y1-en-${index}`,year:1,title:x[1] as string,english:x[2] as string,day:x[3] as number,start:x[4] as number,span:x[5] as number,room:x[6] as string,majors:[String(x[7]).replace(/\d/g,'') as Major],groups:[x[7] as string],kind:'common',weeks:'4–18周',note:x[0] as string}));

export const timetableEvents:TimetableEvent[]=[
  ...y1English,
  {id:'y1-pe',year:1,title:'体育 I',english:'P.E I',day:0,start:0,span:2,room:'体育场馆',majors:['MAM','ICS'],kind:'shared',weeks:'4–18周'},
  {id:'y1-found-mi-1',year:1,title:'微积分数学基础 / 序列与级数',english:'MFC / SAS',day:0,start:2,span:2,room:'N315',majors:['MAM','ICS'],kind:'shared',weeks:'4–16周',track:'dual'},
  {id:'y1-found-es-1',year:1,title:'微积分数学基础 / 序列与级数',english:'MFC / SAS',day:0,start:0,span:2,room:'N315',majors:['Econ','Stat'],kind:'shared',weeks:'4–16周',track:'dual'},
  {id:'y1-found-mi-2',year:1,title:'MFC / SAS 课程',day:2,start:5,span:2,room:'N315',majors:['MAM','ICS'],kind:'shared',weeks:'4–16周',track:'dual'},
  {id:'y1-found-es-2',year:1,title:'MFC / SAS 课程',day:2,start:0,span:2,room:'N315',majors:['Econ','Stat'],kind:'shared',weeks:'4–16周',track:'dual'},
  {id:'y1-found-mi-3',year:1,title:'MFC / SAS Seminar',day:3,start:5,span:2,room:'N415',majors:['MAM','ICS'],kind:'shared',weeks:'4–16周',track:'dual'},
  {id:'y1-found-es-3',year:1,title:'MFC / SAS Seminar',day:3,start:9,span:2,room:'N415',majors:['Econ','Stat'],kind:'shared',weeks:'4–16周',track:'dual'},
  {id:'y1-single-ra',year:1,title:'实分析',english:'RA · Real Analysis',day:1,start:1,span:3,room:'知产218',majors:'all',kind:'common',weeks:'6–17周',track:'single',teacher:'肖亮海'},
  {id:'y1-single-sas',year:1,title:'序列与级数',english:'SAS · Sequences and Series',day:1,start:7,span:2,room:'N423',majors:'all',kind:'common',weeks:'6–14周',track:'single',teacher:'肖亮海'},
  {id:'y1-ide-mi',year:1,title:'思想道德与法治',english:'Ideological Morality and Rule of Law',day:2,start:5,span:2,room:'N415',majors:['MAM','ICS'],kind:'shared',weeks:'4–18周'},
  {id:'y1-ide-es',year:1,title:'思想道德与法治',english:'Ideological Morality and Rule of Law',day:2,start:9,span:2,room:'N415',majors:['Econ','Stat'],kind:'shared',weeks:'4–18周'},
  {id:'y1-military-mi',year:1,title:'军事理论与国家安全教育',day:4,start:2,span:2,room:'N415',majors:['MAM','ICS'],kind:'shared',weeks:'4–18周'},
  {id:'y1-military-es',year:1,title:'军事理论与国家安全教育',day:4,start:5,span:2,room:'N415',majors:['Econ','Stat'],kind:'shared',weeks:'4–18周'},
  {id:'y1-art',year:1,title:'艺术体验与审美鉴赏',day:3,start:7,span:2,room:'待通知',majors:'all',kind:'common'},
  {id:'y1-mental-mam',year:1,title:'大学生心理健康',day:3,start:2,span:2,room:'待通知',majors:['MAM'],kind:'major',weeks:'4–18周'},
  {id:'y1-mental-ics',year:1,title:'大学生心理健康',day:3,start:2,span:2,room:'待通知',majors:['ICS'],kind:'major',weeks:'4–18周'},
  {id:'y1-mental-econ',year:1,title:'大学生心理健康',day:2,start:5,span:2,room:'待通知',majors:['Econ'],kind:'major',weeks:'4–18周'},
  {id:'y1-mental-stat',year:1,title:'大学生心理健康',day:2,start:2,span:2,room:'待通知',majors:['Stat'],kind:'major',weeks:'4–18周'},
  {id:'y1-c-mam',year:1,title:'C语言程序设计',english:'C Programming',day:2,start:0,span:2,room:'N419',majors:['MAM'],kind:'major',weeks:'4–18周'},
  {id:'y1-c-mam-lab',year:1,title:'C语言程序设计实验',day:2,start:2,span:2,room:'N503/504',majors:['MAM'],kind:'major',weeks:'4–18周'},
  {id:'y1-c-ics',year:1,title:'C语言程序设计',english:'C Programming',day:2,start:7,span:2,room:'N412',majors:['ICS'],kind:'major',weeks:'4–18周'},
  {id:'y1-c-ics-lab',year:1,title:'C语言程序设计实验',day:2,start:9,span:2,room:'N514/515',majors:['ICS'],kind:'major',weeks:'4–18周'},
  {id:'y1-pol-econ',year:1,title:'政治经济学',english:'Political Economics',day:2,start:9,span:2,room:'N424',majors:['Econ'],kind:'major',weeks:'4–18周'},
  {id:'y1-pol-stat',year:1,title:'政治经济学',english:'Political Economics',day:2,start:5,span:2,room:'待通知',majors:['Stat'],kind:'major',weeks:'4–18周'},

  {id:'y2-history-mi',year:2,title:'中国近现代史纲要',english:'Outline of Modern Chinese History',day:0,start:5,span:3,room:'N415',majors:['MAM','ICS'],kind:'shared',weeks:'1–18周'},
  {id:'y2-history-es',year:2,title:'中国近现代史纲要',day:0,start:9,span:3,room:'N415',majors:['Econ','Stat'],kind:'shared',weeks:'1–18周'},
  {id:'y2-fmmva-mi-1',year:2,title:'金融数学 / 多元微积分与向量分析',english:'FM / MVA',day:1,start:0,span:2,room:'N315',majors:['MAM','ICS'],kind:'shared',weeks:'1–16周',track:'dual'},
  {id:'y2-fmmva-es-1',year:2,title:'金融数学 / 多元微积分与向量分析',english:'FM / MVA',day:1,start:2,span:2,room:'N315',majors:['Econ','Stat'],kind:'shared',weeks:'1–16周',track:'dual'},
  {id:'y2-fmmva-mi-2',year:2,title:'FM / MVA 课程',day:3,start:0,span:2,room:'N315',majors:['MAM','ICS'],kind:'shared',weeks:'1–16周',track:'dual'},
  {id:'y2-fmmva-es-2',year:2,title:'FM / MVA 课程',day:3,start:2,span:2,room:'N315',majors:['Econ','Stat'],kind:'shared',weeks:'1–16周',track:'dual'},
  {id:'y2-seminar-mi',year:2,title:'FM / MVA Seminar',day:1,start:7,span:2,room:'N315',majors:['MAM','ICS'],kind:'shared',track:'dual'},
  {id:'y2-seminar-es',year:2,title:'FM / MVA Seminar',day:1,start:5,span:2,room:'N315',majors:['Econ','Stat'],kind:'shared',track:'dual'},
  {id:'y2-seminar-fri-mi',year:2,title:'FM / MVA Seminar',day:4,start:0,span:2,room:'N415',majors:['MAM','ICS'],kind:'shared',track:'dual'},
  {id:'y2-seminar-fri-es',year:2,title:'FM / MVA Seminar',day:4,start:0,span:2,room:'N415',majors:['Econ','Stat'],kind:'shared',track:'dual'},
  {id:'y2-single-fm',year:2,title:'金融数学',english:'FM · Financial Mathematics',day:1,start:9,span:3,room:'N416',majors:'all',kind:'common',weeks:'6–17周',track:'single',teacher:'肖亮海'},
  {id:'y2-single-mva',year:2,title:'多元与向量分析',english:'MVA · Multivariable & Vector Analysis',day:3,start:2,span:3,room:'N423',majors:'all',kind:'common',weeks:'6–17周',track:'single',teacher:'吴瑞雯'},
  {id:'y2-pe',year:2,title:'体育 II',english:'P.E II',day:2,start:0,span:2,room:'体育场馆',majors:['MAM','ICS'],kind:'shared',weeks:'1–18周'},
  {id:'y2-matlab',year:2,title:'Matlab程序设计',english:'Matlab Programming',day:2,start:2,span:2,room:'N217',majors:['MAM','ICS'],kind:'shared',weeks:'1–18周'},
  {id:'y2-matlab-lab',year:2,title:'Matlab程序设计实验',day:2,start:5,span:3,room:'MAM N504 / ICS N503',majors:['MAM','ICS'],kind:'shared',weeks:'1–18周'},
  {id:'y2-physics',year:2,title:'大学物理 I',english:'College Physics I',day:2,start:5,span:2,room:'N327',majors:['MAM'],kind:'major',weeks:'1–18周'},
  {id:'y2-physics-2',year:2,title:'大学物理 I',day:3,start:2,span:2,room:'N527',majors:['MAM'],kind:'major',weeks:'1–18周'},
  {id:'y2-algebra-lab',year:2,title:'数值代数实验',english:'Numerical Algebra Lab',day:1,start:2,span:2,room:'N502',majors:['ICS'],kind:'major',weeks:'1–18周'},
  {id:'y2-algebra',year:2,title:'数值代数',english:'Numerical Algebra',day:1,start:9,span:3,room:'N410',majors:['ICS'],kind:'major',weeks:'1–18周'},
  {id:'y2-micro',year:2,title:'中级微观经济学',english:'Intermediate Microeconomics',day:0,start:5,span:3,room:'Econ N310 / Stat N410',majors:['Econ','Stat'],kind:'shared',weeks:'1–18周'},
  {id:'y2-money',year:2,title:'货币金融学',english:'Monetary Finance',day:2,start:5,span:2,room:'知产207',majors:['Econ'],kind:'major',weeks:'1–18周'},
  {id:'y2-statsoft',year:2,title:'统计软件',english:'Statistics Software',day:3,start:9,span:2,room:'N504',majors:['Stat'],kind:'major',weeks:'1–18周'},
  {id:'y2-opt-mi-am',year:2,title:'英语选修（三选一）',english:'UK & USA / Identity / Practical English',day:0,start:2,span:2,room:'N432 / N426 / N423',majors:['MAM','ICS'],kind:'optional',weeks:'1–18周'},
  {id:'y2-opt-es-am',year:2,title:'英语选修（三选一）',english:'UK & USA / Identity / Practical English',day:0,start:0,span:2,room:'N432 / N426 / N423',majors:['Econ','Stat'],kind:'optional',weeks:'1–18周'},
  {id:'y2-opt-all',year:2,title:'英美历史与文化（选修）',english:'The History and Culture of UK and USA',day:2,start:9,span:2,room:'N426',majors:'all',kind:'optional',weeks:'1–18周'},
  {id:'y2-ielts-12',year:2,title:'雅思课程',english:'IELTS Course',day:1,start:2,span:2,room:'E1 N432 / E2 N426',majors:['MAM'],groups:['MAM1','MAM2'],kind:'common',weeks:'1–18周'},
  {id:'y2-ielts-34',year:2,title:'雅思课程',day:1,start:5,span:2,room:'E3 N432 / E4 N426',majors:['ICS'],groups:['ICS1','ICS2'],kind:'common',weeks:'1–18周'},
  {id:'y2-ielts-5',year:2,title:'雅思课程',day:4,start:5,span:2,room:'E5 N432',majors:['Econ'],groups:['Econ1'],kind:'common',weeks:'1–18周'},
  {id:'y2-ielts-6',year:2,title:'雅思课程',day:2,start:0,span:2,room:'E6 N423',majors:['Econ'],groups:['Econ2'],kind:'common',weeks:'1–18周'},
  {id:'y2-ielts-78',year:2,title:'雅思课程',day:2,start:5,span:2,room:'E7 N432 / E8 N423',majors:['Stat'],groups:['Stat1','Stat2'],kind:'common',weeks:'1–18周'},

  {id:'y3-marx',year:3,title:'马克思主义基本原理',english:'Outline of Marxism Basic Principles',day:0,start:5,span:3,room:'Econ/Stat N315 · MAM/ICS N217',majors:'all',kind:'common',weeks:'1–18周'},
  {id:'y3-ipco-es-tue',year:3,title:'整数规划及组合优化 / 博弈论与多准则决策',english:'IPCO / GTMCD',day:1,start:0,span:2,room:'N415',majors:['Econ','Stat'],kind:'shared',weeks:'1–16周',track:'dual'},
  {id:'y3-ipco-mi-tue',year:3,title:'IPCO / GTMCD',day:1,start:2,span:2,room:'N415',majors:['MAM','ICS'],kind:'shared',weeks:'1–16周',track:'dual'},
  {id:'y3-ipco-mi-wed',year:3,title:'IPCO / GTMCD',day:2,start:0,span:2,room:'N415',majors:['MAM','ICS'],kind:'shared',weeks:'1–16周',track:'dual'},
  {id:'y3-ipco-es-wed',year:3,title:'IPCO / GTMCD',day:2,start:2,span:2,room:'N415',majors:['Econ','Stat'],kind:'shared',weeks:'1–16周',track:'dual'},
  {id:'y3-ipco-mi-thu',year:3,title:'IPCO / GTMCD',day:3,start:0,span:2,room:'N415',majors:['MAM','ICS'],kind:'shared',weeks:'1–16周',track:'dual'},
  {id:'y3-ipco-es-thu',year:3,title:'IPCO / GTMCD',day:3,start:2,span:2,room:'N415',majors:['Econ','Stat'],kind:'shared',weeks:'1–16周',track:'dual'},
  {id:'y3-ipco-seminar',year:3,title:'IPCO / GTMCD Seminar & Q&A',day:1,start:5,span:3,room:'N217',majors:'all',kind:'common',weeks:'1–16周',track:'dual'},
  {id:'y3-ipco-seminar-2',year:3,title:'IPCO / GTMCD Seminar & Q&A',day:3,start:5,span:4,room:'N419 / N415',majors:'all',kind:'common',weeks:'1–16周',track:'dual'},
  {id:'y3-single-gtmcd',year:3,title:'博弈论与多准则决策',english:'GTMCD · Game Theory and Multi Criteria Decision Making',day:1,start:1,span:3,room:'N418',majors:'all',kind:'common',weeks:'6–17周',track:'single',teacher:'戴天仕'},
  {id:'y3-single-ipco',year:3,title:'整数规划与组合优化',english:'IPCO · Integer Programming and Combinatorial Optimisation',day:2,start:1,span:3,room:'N426',majors:'all',kind:'common',weeks:'6–17周',track:'single',teacher:'吴乐秦'},
  {id:'y3-real',year:3,title:'实变函数',english:'Theory of Real Variable Function',day:4,start:1,span:3,room:'N211',majors:['MAM'],kind:'major',weeks:'1–18周'},
  {id:'y3-topology',year:3,title:'一般拓扑学',english:'General Topology',day:0,start:9,span:3,room:'N411',majors:['MAM'],kind:'major',weeks:'1–18周'},
  {id:'y3-info',year:3,title:'信息论与编码',english:'Information Theory and Coding',day:2,start:5,span:3,room:'N509',majors:['ICS'],kind:'major',weeks:'1–18周'},
  {id:'y3-algo-fri',year:3,title:'算法设计与分析',english:'Design and Analysis of Algorithms',day:4,start:1,span:3,room:'N504',majors:['ICS'],kind:'major',weeks:'1–18周'},
  {id:'y3-algo-thu',year:3,title:'算法设计与分析',day:3,start:9,span:3,room:'N412',majors:['ICS'],kind:'major',weeks:'1–18周'},
  {id:'y3-macro',year:3,title:'中级宏观经济学',english:'Intermediate Macroeconomics',day:0,start:1,span:3,room:'N415',majors:['Econ','Stat'],kind:'shared',weeks:'1–18周'},
  {id:'y3-corp',year:3,title:'公司金融',english:'Corporate Finance',day:2,start:5,span:3,room:'N309',majors:['Econ'],kind:'major',weeks:'1–18周'},
  {id:'y3-invest',year:3,title:'投资学',english:'Investments',day:4,start:5,span:3,room:'N305',majors:['Econ'],kind:'major',weeks:'1–18周'},
  {id:'y3-stoch',year:3,title:'随机过程',english:'Stochastic Process',day:2,start:5,span:3,room:'N527',majors:['Stat'],kind:'major',weeks:'1–18周'},
  {id:'y3-math-econ-1',year:3,title:'数学经济建模',english:'Mathematical Economic Modelling',day:1,start:2,span:2,room:'N417',majors:['Stat'],kind:'major',weeks:'1–18周'},
  {id:'y3-math-econ-2',year:3,title:'数学经济建模',day:1,start:7,span:2,room:'N504',majors:['Stat'],kind:'major',weeks:'1–18周'},

  {id:'y4-multi',year:4,title:'跨国企业管理',english:'Multinational Enterprise Management (O)',day:0,start:5,span:3,room:'N304',majors:'all',kind:'optional',weeks:'1–18周'},
  {id:'y4-history',year:4,title:'统计学史',english:'History of Statistics (O)',day:1,start:9,span:3,room:'N420',majors:'all',kind:'optional',weeks:'1–18周'},
  {id:'y4-public',year:4,title:'公共经济学',english:'Public Economics (O)',day:3,start:5,span:3,room:'N310',majors:['Econ','Stat'],kind:'optional',weeks:'1–18周'},
  {id:'y4-environment',year:4,title:'环境经济学',english:'Environmental Economics (O)',day:3,start:9,span:3,room:'N310',majors:['Econ','Stat'],kind:'optional',weeks:'1–18周'},
  {id:'y4-modelling',year:4,title:'统计建模',english:'Statistical Modelling (O)',day:3,start:5,span:3,room:'N410',majors:['Econ','Stat'],kind:'optional',weeks:'1–18周'},
  {id:'y4-causal',year:4,title:'因果推断导论',english:'Introduction to Causal Inference (O)',day:1,start:1,span:3,room:'N311',majors:['MAM','ICS'],kind:'optional',weeks:'1–18周'},
  {id:'y4-multivariate',year:4,title:'应用多元统计分析',english:'Applied Multivariate Statistical Analysis (O)',day:2,start:5,span:3,room:'N418',majors:['MAM','ICS'],kind:'optional',weeks:'1–18周'},
  {id:'y4-intelligence',year:4,title:'计算智能',english:'Computational Intelligence (O)',day:4,start:5,span:3,room:'N311',majors:['MAM','ICS'],kind:'optional',weeks:'1–18周'},
  {id:'y4-macro',year:4,title:'宏观经济学导论',english:'Introduction to Macroeconomics (O)',day:0,start:5,span:3,room:'N412',majors:['MAM'],kind:'optional',weeks:'1–18周'},
  {id:'y4-data',year:4,title:'数据分析',english:'Data Analysis (O)',day:2,start:5,span:3,room:'N431',majors:['ICS'],kind:'optional',weeks:'1–18周'},
];

export const majors:{id:Major;label:string;name:string}[]=[
  {id:'MAM',label:'MAM',name:'数学与应用数学'}, {id:'ICS',label:'ICS',name:'信息与计算科学'},
  {id:'Econ',label:'ECON',name:'经济学'}, {id:'Stat',label:'STAT',name:'经统'},
];

export const times=[['1','08:30','09:15'],['2','09:25','10:10'],['3','10:30','11:15'],['4','11:25','12:10'],['5','午间',''],['6','14:00','14:45'],['7','14:55','15:40'],['8','15:50','16:35'],['9','16:45','17:30'],['10','18:30','19:15'],['11','19:25','20:10'],['12','20:20','21:05']];
